### ISSUE TITLE
Build Error while enabling proguard

### ISSUE THREAD

**Issue by tamacroft** [margelo/react-native-skottie#42]
```FATAL EXCEPTION: mqt_native_modules
Process: com.xxx.android, PID: 25405
com.facebook.react.common.JavascriptException: Error: Exception in HostFunction: java.lang.NoSuchMethodError: no non-static method "Lcom/skiaskottie/DotLottieReader;.readDotLottie(Ljava/lang/String;)Ljava/lang/String;", js engine: hermes, stack:
callNativeSyncHook@1:94633
nonPromiseMethodWrapper@1:91639
anonymous@1:1776457
loadModuleImplementation@1:70641
guardedLoadModule@1:70183
metroRequire@1:69805
anonymous@1:1775609
loadModuleImplementation@1:70641
guardedLoadModule@1:70140
metroRequire@1:69805
LoadMore@1:2046900
renderWithHooks@1:363068
beginWork$1@1:404988
performUnitOfWork@1:391547
workLoopSync@1:391407
renderRootSync@1:391288
performSyncWorkOnRoot@1:388680
flushSyncCallbacks@1:352705
batchedUpdatesImpl@1:405387
batchedUpdates@1:345516
_receiveRootNodeIDEvent@1:345801
receiveTouches@1:400068
__callFunction@1:95893
anonymous@1:94195
__guard@1:95153
callFunctionReturnFlushedQueue@1:94153

	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(Unknown Source:75)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source:142)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:21)
	at com.facebook.jni.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(Unknown Source:37)
	at java.lang.Thread.run(Thread.java:1012)
```
	
Im using v2.1.4 with rn v0.73.8

**Comment by tamacroft** [comment]
when im run on debug its work, but when i build to apk file then install on device, message error like this
```
TypeError: Cannot read property 'Skottie' of undefined

This error is located at:
    in LoadMore
    in RCTView
    in Unknown
    in VirtualizedListCellContextProvider
    in RCTView
    in Unknown
    in RCTScrollView
    in AndroidSwipeRefreshLayout
    in RefreshControl
    in ScrollView
    in ScrollView
    in VirtualizedListContextProvider
    in VirtualizedList
    in FlatList
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in KeyboardAvoidingView
    in RCTView
    in Unknown
    in Unknown
    in ListAssetScreen
    in StaticContainer
    in EnsureSingleNavigator
    in SceneView
    in RCTView
    in Unknown
    in DebugContainer
    in MaybeNestedStack
    in RCTView
    in Unknown
    in RNSScreen
    in Unknown
    in Suspender
    in Suspense
    in Freeze
    in DelayedFreeze
    in InnerScreen
    in Screen
    in SceneView
    in Suspender
    in Suspense
    in Freeze
    in DelayedFreeze
    in RNSScreenStack
    in ScreenStack
    in NativeStackViewInner
    in RCTView
    in Unknown
    in SafeAreaProviderCompat
    in NativeStackView
    in PreventRemoveProvider
    in NavigationContent
    in Unknown
    in NativeStackNavigator
    in AppStack
    in RNCSafeAreaView
    in Unknown
    in PortalProviderComponent
    in BottomSheetModalProviderWrapper
    in RNCSafeAreaProvider
    in SafeAreaProvider
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner
    in AppNavigator
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in MenuProvider
    in PortalProviderComponent
    in BottomSheetModalProviderWrapper
    in RNGestureHandlerRootView
    in GestureHandlerRootView
    in App
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in AppContainer, js engine: hermes

**Comment by idrakimuhamad** [comment]
Second that, getting this in release build. I think may need to add some of the skottie classes inside the proguard.

**Comment by idrakimuhamad** [comment]
Adding this into proguard rules solves it.

```
-keep class com.skiaskottie.** { *; }
```
